### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by sectsect** [artofrawr/webpack-iconfont-plugin#2]
Thanks for useful package.

Can we have file output for pure css or PostCSS?
I need it for PostCSS.

**Comment by artofrawr** [comment]
You can already do that. You can create your own nunjucks template, that can output any format you'd like and pass that template in the config. Something along these lines would work:

```
new IconfontPlugin({
    svgs: resolve(__dirname, 'assets/icons/*.svg'),
    fonts: resolve(__dirname, 'static/fonts/iconfont'),
    styles: resolve(__dirname, 'assets/css/_iconfont.scss'),
    template: resolve(__dirname, 'assets/icons/_template.css.njk')
})
```
