### ISSUE TITLE
webpack2 keeps rebuilding

### ISSUE THREAD

**Issue by berkandirim** [artofrawr/webpack-iconfont-plugin#4]
I have the following setup in my nuxtjs project. Somehow the generated files triggers a rebuild and it keep rebuilding and rebuilding. How to limit the build only if there's a new svg file?

```
new IconfontPlugin({
        svgs: resolve(__dirname, 'assets/icons/*.svg'),
        fonts: resolve(__dirname, 'static/fonts/iconfont'),
        styles: resolve(__dirname, 'assets/css/_iconfont.scss'),
        cssFontPath: '/static/fonts/iconfont/',
        fontName: 'icon',
        template: resolve(__dirname, 'assets/iconfont-templates/template.scss.njk')
      })
```

**Comment by artofrawr** [comment]
This part of the plugin definitely needs some improvement. As a temporary solution, you could add the paths of the generated files to a [webpack.WatchIgnorePlugin](https://github.com/webpack/docs/wiki/list-of-plugins#watchignoreplugin), so they are not being watched anymore and can't trigger a rebuild. For your example, you'd have to add the following to the plugins in your webpack config:

```
new webpack.WatchIgnorePlugin([
    resolve(__dirname, 'static/fonts/iconfont'),
    resolve(__dirname, 'assets/css/_iconfont.scss'),
]),
```
